
def pais_alfa2(pais):
    nombre_pais = ''
    if pais == 'AD':    nombre_pais = 'Andorra'
    if pais == 'AD':    nombre_pais = 'Andorra'
    if pais == 'AE':    nombre_pais = 'Emiratos Árabes Unidos'
    if pais == 'AF':    nombre_pais = 'Afganistán'
    if pais == 'AG':    nombre_pais = 'Antigua y Barbuda'
    if pais == 'AI':    nombre_pais = 'Anguila'
    if pais == 'AL':    nombre_pais = 'Albania'
    if pais == 'AM':    nombre_pais = 'Armenia'
    if pais == 'AN':    nombre_pais = 'Antillas Neerlandesas'
    if pais == 'AO':    nombre_pais = 'Angola'
    if pais == 'AQ':    nombre_pais = 'Antártida'
    if pais == 'AR':    nombre_pais = 'Argentina'
    if pais == 'AS':    nombre_pais = 'Samoa Americana'
    if pais == 'AT':    nombre_pais = 'Austria'
    if pais == 'AU':    nombre_pais = 'Australia'
    if pais == 'AW':    nombre_pais = 'Aruba'
    if pais == 'AX':    nombre_pais = 'Islas Áland'
    if pais == 'AZ':    nombre_pais = 'Azerbaiyán'
    if pais == 'BA':    nombre_pais = 'Bosnia y Herzegovina'
    if pais == 'BB':    nombre_pais = 'Barbados'
    if pais == 'BD':    nombre_pais = 'Bangladesh'
    if pais == 'BE':    nombre_pais = 'Bélgica'
    if pais == 'BF':    nombre_pais = 'Burkina Faso'
    if pais == 'BG':    nombre_pais = 'Bulgaria'
    if pais == 'BH':    nombre_pais = 'Bahréin'
    if pais == 'BI':    nombre_pais = 'Burundi'
    if pais == 'BJ':    nombre_pais = 'Benin'
    if pais == 'BL':    nombre_pais = 'San Bartolomé'
    if pais == 'BM':    nombre_pais = 'Bermudas'
    if pais == 'BN':    nombre_pais = 'Brunéi'
    if pais == 'BO':    nombre_pais = 'Bolivia'
    if pais == 'BR':    nombre_pais = 'Brasil'
    if pais == 'BS':    nombre_pais = 'Bahamas'
    if pais == 'BT':    nombre_pais = 'Bhután'
    if pais == 'BV':    nombre_pais = 'Isla Bouvet'
    if pais == 'BW':    nombre_pais = 'Botsuana'
    if pais == 'BY':    nombre_pais = 'Belarús'
    if pais == 'BZ':    nombre_pais = 'Belice'
    if pais == 'CA':    nombre_pais = 'Canadá'
    if pais == 'CC':    nombre_pais = 'Islas Cocos'
    if pais == 'CF':    nombre_pais = 'República Centro-Africana'
    if pais == 'CG':    nombre_pais = 'Congo'
    if pais == 'CH':    nombre_pais = 'Suiza'
    if pais == 'CI':    nombre_pais = 'Costa de Marfil'
    if pais == 'CK':    nombre_pais = 'Islas Cook'
    if pais == 'CL':    nombre_pais = 'Chile'
    if pais == 'CM':    nombre_pais = 'Camerún'
    if pais == 'CN':    nombre_pais = 'China'
    if pais == 'CO':    nombre_pais = 'Colombia'
    if pais == 'CR':    nombre_pais = 'Costa Rica'
    if pais == 'CU':    nombre_pais = 'Cuba'
    if pais == 'CV':    nombre_pais = 'Cabo Verde'
    if pais == 'CX':    nombre_pais = 'Islas Christmas'
    if pais == 'CY':    nombre_pais = 'Chipre'
    if pais == 'CZ':    nombre_pais = 'República Checa'
    if pais == 'DE':    nombre_pais = 'Alemania'
    if pais == 'DJ':    nombre_pais = 'Yibuti'
    if pais == 'DK':    nombre_pais = 'Dinamarca'
    if pais == 'DM':    nombre_pais = 'Domínica'
    if pais == 'DO':    nombre_pais = 'República Dominicana'
    if pais == 'DZ':    nombre_pais = 'Argel'
    if pais == 'EC':    nombre_pais = 'Ecuador'
    if pais == 'EE':    nombre_pais = 'Estonia'
    if pais == 'EG':    nombre_pais = 'Egipto'
    if pais == 'EH':    nombre_pais = 'Sahara Occidental'
    if pais == 'ER':    nombre_pais = 'Eritrea'
    if pais == 'ES':    nombre_pais = 'España'
    if pais == 'ET':    nombre_pais = 'Etiopía'
    if pais == 'FI':    nombre_pais = 'Finlandia'
    if pais == 'FJ':    nombre_pais = 'Fiji'
    if pais == 'FK':    nombre_pais = 'Islas Malvinas'
    if pais == 'FM':    nombre_pais = 'Micronesia'
    if pais == 'FO':    nombre_pais = 'Islas Faroe'
    if pais == 'FR':    nombre_pais = 'Francia'
    if pais == 'GA':    nombre_pais = 'Gabón'
    if pais == 'GB':    nombre_pais = 'Reino Unido'
    if pais == 'GD':    nombre_pais = 'Granada'
    if pais == 'GE':    nombre_pais = 'Georgia'
    if pais == 'GF':    nombre_pais = 'Guayana Francesa'
    if pais == 'GG':    nombre_pais = 'Guernsey'
    if pais == 'GH':    nombre_pais = 'Ghana'
    if pais == 'GI':    nombre_pais = 'Gibraltar'
    if pais == 'GL':    nombre_pais = 'Groenlandia'
    if pais == 'GM':    nombre_pais = 'Gambia'
    if pais == 'GN':    nombre_pais = 'Guinea'
    if pais == 'GP':    nombre_pais = 'Guadalupe'
    if pais == 'GQ':    nombre_pais = 'Guinea Ecuatorial'
    if pais == 'GR':    nombre_pais = 'Grecia'
    if pais == 'GS':    nombre_pais = 'Georgia del Sur e Islas Sandwich del Sur'
    if pais == 'GT':    nombre_pais = 'Guatemala'
    if pais == 'GU':    nombre_pais = 'Guam'
    if pais == 'GW':    nombre_pais = 'Guinea-Bissau'
    if pais == 'GY':    nombre_pais = 'Guayana'
    if pais == 'HK':    nombre_pais = 'Hong Kong'
    if pais == 'HM':    nombre_pais = 'Islas Heard y McDonald'
    if pais == 'HN':    nombre_pais = 'Honduras'
    if pais == 'HR':    nombre_pais = 'Croacia'
    if pais == 'HT':    nombre_pais = 'Haití'
    if pais == 'HU':    nombre_pais = 'Hungría'
    if pais == 'ID':    nombre_pais = 'Indonesia'
    if pais == 'IE':    nombre_pais = 'Irlanda'
    if pais == 'IL':    nombre_pais = 'Israel'
    if pais == 'IM':    nombre_pais = 'Isla de Man'
    if pais == 'IN':    nombre_pais = 'India'
    if pais == 'IO':    nombre_pais = 'Territorio Británico del Océano Índico'
    if pais == 'IQ':    nombre_pais = 'Irak'
    if pais == 'IR':    nombre_pais = 'Irán'
    if pais == 'IS':    nombre_pais = 'Islandia'
    if pais == 'IT':    nombre_pais = 'Italia'
    if pais == 'JE':    nombre_pais = 'Jersey'
    if pais == 'JM':    nombre_pais = 'Jamaica'
    if pais == 'JO':    nombre_pais = 'Jordania'
    if pais == 'JP':    nombre_pais = 'Japón'
    if pais == 'KE':    nombre_pais = 'Kenia'
    if pais == 'KG':    nombre_pais = 'Kirguistán'
    if pais == 'KH':    nombre_pais = 'Camboya'
    if pais == 'KI':    nombre_pais = 'Kiribati'
    if pais == 'KM':    nombre_pais = 'Comoros'
    if pais == 'KN':    nombre_pais = 'San Cristóbal y Nieves'
    if pais == 'KP':    nombre_pais = 'Corea del Norte'
    if pais == 'KR':    nombre_pais = 'Corea del Sur'
    if pais == 'KW':    nombre_pais = 'Kuwait'
    if pais == 'KY':    nombre_pais = 'Islas Caimán'
    if pais == 'KZ':    nombre_pais = 'Kazajstán'
    if pais == 'LA':    nombre_pais = 'Laos'
    if pais == 'LB':    nombre_pais = 'Líbano'
    if pais == 'LC':    nombre_pais = 'Santa Lucía'
    if pais == 'LI':    nombre_pais = 'Liechtenstein'
    if pais == 'LK':    nombre_pais = 'Sri Lanka'
    if pais == 'LR':    nombre_pais = 'Liberia'
    if pais == 'LS':    nombre_pais = 'Lesotho'
    if pais == 'LT':    nombre_pais = 'Lituania'
    if pais == 'LU':    nombre_pais = 'Luxemburgo'
    if pais == 'LV':    nombre_pais = 'Letonia'
    if pais == 'LY':    nombre_pais = 'Libia'
    if pais == 'MA':    nombre_pais = 'Marruecos'
    if pais == 'MC':    nombre_pais = 'Mónaco'
    if pais == 'MD':    nombre_pais = 'Moldova'
    if pais == 'ME':    nombre_pais = 'Montenegro'
    if pais == 'MG':    nombre_pais = 'Madagascar'
    if pais == 'MH':    nombre_pais = 'Islas Marshall'
    if pais == 'MK':    nombre_pais = 'Macedonia'
    if pais == 'ML':    nombre_pais = 'Mali'
    if pais == 'MM':    nombre_pais = 'Myanmar'
    if pais == 'MN':    nombre_pais = 'Mongolia'
    if pais == 'MO':    nombre_pais = 'Macao'
    if pais == 'MQ':    nombre_pais = 'Martinica'
    if pais == 'MR':    nombre_pais = 'Mauritania'
    if pais == 'MS':    nombre_pais = 'Montserrat'
    if pais == 'MT':    nombre_pais = 'Malta'
    if pais == 'MU':    nombre_pais = 'Mauricio'
    if pais == 'MV':    nombre_pais = 'Maldivas'
    if pais == 'MW':    nombre_pais = 'Malawi'
    if pais == 'MX':    nombre_pais = 'México'
    if pais == 'MY':    nombre_pais = 'Malasia'
    if pais == 'MZ':    nombre_pais = 'Mozambique'
    if pais == 'NA':    nombre_pais = 'Namibia'
    if pais == 'NC':    nombre_pais = 'Nueva Caledonia'
    if pais == 'NE':    nombre_pais = 'Níger'
    if pais == 'NF':    nombre_pais = 'Islas Norkfolk'
    if pais == 'NG':    nombre_pais = 'Nigeria'
    if pais == 'NI':    nombre_pais = 'Nicaragua'
    if pais == 'NL':    nombre_pais = 'Países Bajos'
    if pais == 'NO':    nombre_pais = 'Noruega'
    if pais == 'NP':    nombre_pais = 'Nepal'
    if pais == 'NR':    nombre_pais = 'Nauru'
    if pais == 'NU':    nombre_pais = 'Niue'
    if pais == 'NZ':    nombre_pais = 'Nueva Zelanda'
    if pais == 'OM':    nombre_pais = 'Omán'
    if pais == 'PA':    nombre_pais = 'Panamá'
    if pais == 'PE':    nombre_pais = 'Perú'
    if pais == 'PF':    nombre_pais = 'Polinesia Francesa'
    if pais == 'PG':    nombre_pais = 'Papúa Nueva Guinea'
    if pais == 'PH':    nombre_pais = 'Filipinas'
    if pais == 'PK':    nombre_pais = 'Pakistán'
    if pais == 'PL':    nombre_pais = 'Polonia'
    if pais == 'PM':    nombre_pais = 'San Pedro y Miquelón'
    if pais == 'PN':    nombre_pais = 'Islas Pitcairn'
    if pais == 'PR':    nombre_pais = 'Puerto Rico'
    if pais == 'PS':    nombre_pais = 'Palestina'
    if pais == 'PT':    nombre_pais = 'Portugal'
    if pais == 'PW':    nombre_pais = 'Islas Palaos'
    if pais == 'PY':    nombre_pais = 'Paraguay'
    if pais == 'QA':    nombre_pais = 'Qatar'
    if pais == 'RE':    nombre_pais = 'Reunión'
    if pais == 'RO':    nombre_pais = 'Rumanía'
    if pais == 'RS':    nombre_pais = 'Serbia y Montenegro'
    if pais == 'RU':    nombre_pais = 'Rusia'
    if pais == 'RW':    nombre_pais = 'Ruanda'
    if pais == 'SA':    nombre_pais = 'Arabia Saudita'
    if pais == 'SB':    nombre_pais = 'Islas Solomón'
    if pais == 'SC':    nombre_pais = 'Seychelles'
    if pais == 'SD':    nombre_pais = 'Sudán'
    if pais == 'SE':    nombre_pais = 'Suecia'
    if pais == 'SG':    nombre_pais = 'Singapur'
    if pais == 'SH':    nombre_pais = 'Santa Elena'
    if pais == 'SI':    nombre_pais = 'Eslovenia'
    if pais == 'SJ':    nombre_pais = 'Islas Svalbard y Jan Mayen'
    if pais == 'SK':    nombre_pais = 'Eslovaquia'
    if pais == 'SL':    nombre_pais = 'Sierra Leona'
    if pais == 'SM':    nombre_pais = 'San Marino'
    if pais == 'SN':    nombre_pais = 'Senegal'
    if pais == 'SO':    nombre_pais = 'Somalia'
    if pais == 'SR':    nombre_pais = 'Surinam'
    if pais == 'ST':    nombre_pais = 'Santo Tomé y Príncipe'
    if pais == 'SV':    nombre_pais = 'El Salvador'
    if pais == 'SY':    nombre_pais = 'Siria'
    if pais == 'SZ':    nombre_pais = 'Suazilandia'
    if pais == 'TC':    nombre_pais = 'Islas Turcas y Caicos'
    if pais == 'TD':    nombre_pais = 'Chad'
    if pais == 'TF':    nombre_pais = 'Territorios Australes Franceses'
    if pais == 'TG':    nombre_pais = 'Togo'
    if pais == 'TH':    nombre_pais = 'Tailandia'
    if pais == 'TH':    nombre_pais = 'Tanzania'
    if pais == 'TJ':    nombre_pais = 'Tayikistán'
    if pais == 'TK':    nombre_pais = 'Tokelau'
    if pais == 'TL':    nombre_pais = 'Timor-Leste'
    if pais == 'TM':    nombre_pais = 'Turkmenistán'
    if pais == 'TN':    nombre_pais = 'Túnez'
    if pais == 'TO':    nombre_pais = 'Tonga'
    if pais == 'TR':    nombre_pais = 'Turquía'
    if pais == 'TT':    nombre_pais = 'Trinidad y Tobago'
    if pais == 'TV':    nombre_pais = 'Tuvalu'
    if pais == 'TW':    nombre_pais = 'Taiwán'
    if pais == 'UA':    nombre_pais = 'Ucrania'
    if pais == 'UG':    nombre_pais = 'Uganda'
    if pais == 'US':    nombre_pais = 'Estados Unidos de América'
    if pais == 'UY':    nombre_pais = 'Uruguay'
    if pais == 'UZ':    nombre_pais = 'Uzbekistán'
    if pais == 'VA':    nombre_pais = 'Ciudad del Vaticano'
    if pais == 'VC':    nombre_pais = 'San Vicente y las Granadinas'
    if pais == 'VE':    nombre_pais = 'Venezuela'
    if pais == 'VG':    nombre_pais = 'Islas Vírgenes Británicas'
    if pais == 'VI':    nombre_pais = 'Islas Vírgenes de los Estados Unidos de América'
    if pais == 'VN':    nombre_pais = 'Vietnam'
    if pais == 'VU':    nombre_pais = 'Vanuatu'
    if pais == 'WF':    nombre_pais = 'Wallis y Futuna'
    if pais == 'WS':    nombre_pais = 'Samoa'
    if pais == 'YE':    nombre_pais = 'Yemen'
    if pais == 'YT':    nombre_pais = 'Mayotte'
    if pais == 'ZA':    nombre_pais = 'Sudáfrica'
    return(nombre_pais)